// Shared PBR materials (MeshPhysical) with procedural texture detail. Physically plausible values:
// metals metalness 1 with their F0 tint as colour; lacquer = clearcoat; dielectrics metalness 0.
import * as THREE from 'three';
import { brassRoughness, brushedNormal, cork, fineGrainNormal, leather, nacre, reed } from './render/textures';

export const HIGHLIGHT = new THREE.Color(0x3fa9ff);
export const ACTIVE = new THREE.Color(0xff9a3c);

/** colour of the tarnish/patina that collects in crevices (where the `cavity` attribute is > 0) */
const PATINA = new THREE.Color(0x4a3a1c);

/**
 * Adds a per-vertex `cavity` attribute (0…1, generated by the geometry code at chimney bases, under
 * posts, in the bow crease) to a physical material: darker, rougher, browner patina and occluded
 * ambient light there. Meshes without the attribute read 0 → unaffected.
 */
export function withCavity<T extends THREE.MeshPhysicalMaterial>(m: T, strength = 1): T {
  m.onBeforeCompile = (s) => {
    s.uniforms.uPatina = { value: PATINA };
    s.uniforms.uCavStrength = { value: strength };
    s.vertexShader = s.vertexShader
      .replace('#include <common>', '#include <common>\nattribute float cavity;\nvarying float vCavity;')
      .replace('#include <begin_vertex>', '#include <begin_vertex>\nvCavity = cavity;');
    s.fragmentShader = s.fragmentShader
      .replace('#include <common>', '#include <common>\nvarying float vCavity;\nuniform vec3 uPatina;\nuniform float uCavStrength;')
      .replace('#include <color_fragment>', '#include <color_fragment>\nfloat cav = clamp(vCavity * uCavStrength, 0.0, 1.0);\ndiffuseColor.rgb = mix(diffuseColor.rgb, uPatina, cav * 0.6);')
      .replace('#include <roughnessmap_fragment>', '#include <roughnessmap_fragment>\nroughnessFactor = mix(roughnessFactor, 0.55, cav);')
      .replace(
        '#include <aomap_fragment>',
        `#include <aomap_fragment>
        float cavAO = 1.0 - 0.7 * cav;
        reflectedLight.indirectDiffuse *= cavAO;
        reflectedLight.indirectSpecular *= cavAO;
        #ifdef USE_CLEARCOAT
          clearcoatSpecularIndirect *= cavAO;
        #endif`,
      );
  };
  m.customProgramCacheKey = () => `cavity${strength}`;
  return m;
}

function tex<T extends THREE.Texture>(t: T, rx: number, ry: number): T {
  const c = t.clone();
  c.repeat.set(rx, ry);
  c.needsUpdate = true;
  return c;
}

export class Materials {
  // texture detail is mapped in metres by the geometry code (uv = metres × UV_PER_M)
  readonly brass: THREE.MeshPhysicalMaterial;
  /** inside of tone-hole chimneys and other recesses */
  readonly brassDark: THREE.MeshPhysicalMaterial;
  /** key cups, arms, touches (lacquered brass, slightly lighter / more polished) */
  readonly keyBrass: THREE.MeshPhysicalMaterial;
  /** rods, posts, hinge screws, guards' wire: nickel-silver */
  readonly nickel: THREE.MeshPhysicalMaterial;
  readonly pad: THREE.MeshPhysicalMaterial;
  readonly resonator: THREE.MeshPhysicalMaterial;
  readonly pearl: THREE.MeshPhysicalMaterial;
  readonly rubber: THREE.MeshPhysicalMaterial;
  readonly mpInterior: THREE.MeshPhysicalMaterial;
  readonly cutFace: THREE.MeshStandardMaterial;
  readonly reed: THREE.MeshPhysicalMaterial;
  readonly ligature: THREE.MeshPhysicalMaterial;
  readonly cork: THREE.MeshPhysicalMaterial;
  readonly handle = new THREE.MeshStandardMaterial({ color: 0xffffff, emissive: 0x2a6fd6, emissiveIntensity: 0.8, roughness: 0.3, transparent: true, opacity: 0.9, depthTest: false });

  /** materials that fade in X-ray mode (instrument shell, mouthpiece shell; clones register here) */
  private xrayFade = new Set<THREE.Material>();
  private xray = false;
  private xrayCbs: ((on: boolean) => void)[] = [];

  constructor() {
    const bn = brushedNormal();
    const rough = brassRoughness();
    this.brass = withCavity(new THREE.MeshPhysicalMaterial({
      color: 0xe2b864,
      metalness: 1,
      roughness: 0.3,
      roughnessMap: rough,
      normalMap: bn,
      normalScale: new THREE.Vector2(0.025, 0.025),
      clearcoat: 1,
      clearcoatRoughness: 0.07,
      envMapIntensity: 1,
      side: THREE.FrontSide,
    }));
    this.brass.name = 'brass';
    this.brassDark = new THREE.MeshPhysicalMaterial({ color: 0x8a6528, metalness: 1, roughness: 0.45, side: THREE.BackSide });
    this.keyBrass = withCavity(new THREE.MeshPhysicalMaterial({
      color: 0xe8c074,
      metalness: 1,
      roughness: 0.24,
      roughnessMap: rough,
      normalMap: bn,
      normalScale: new THREE.Vector2(0.04, 0.04),
      clearcoat: 1,
      clearcoatRoughness: 0.05,
    }));
    this.keyBrass.name = 'keyBrass';
    this.nickel = new THREE.MeshPhysicalMaterial({
      color: 0xd9d6cf, metalness: 1, roughness: 0.2, normalMap: bn, normalScale: new THREE.Vector2(0.05, 0.05),
    });
    const lt = leather();
    this.pad = new THREE.MeshPhysicalMaterial({
      color: 0xffffff, map: tex(lt.map, 3, 3), normalMap: tex(lt.normal, 3, 3), normalScale: new THREE.Vector2(0.5, 0.5),
      roughness: 0.68, metalness: 0, sheen: 0.4, sheenColor: new THREE.Color(0xd9b89a), sheenRoughness: 0.6,
    });
    this.resonator = new THREE.MeshPhysicalMaterial({ color: 0xdedcd6, roughness: 0.14, metalness: 1 });
    const nc = nacre();
    this.pearl = new THREE.MeshPhysicalMaterial({
      color: 0xffffff, map: nc.map, roughness: 0.12, metalness: 0, clearcoat: 1, clearcoatRoughness: 0.04,
      iridescence: 1, iridescenceIOR: 1.45, iridescenceThicknessRange: [180, 520], iridescenceThicknessMap: nc.thickness,
      sheen: 0.25, sheenColor: new THREE.Color(0xffe9f0),
    });
    this.rubber = new THREE.MeshPhysicalMaterial({
      color: 0x0d0d0f, roughness: 0.34, metalness: 0, clearcoat: 0.55, clearcoatRoughness: 0.16,
      normalMap: fineGrainNormal(), normalScale: new THREE.Vector2(0.04, 0.04), side: THREE.DoubleSide,
    });
    this.mpInterior = new THREE.MeshPhysicalMaterial({
      color: 0x2bd4c5, roughness: 0.45, metalness: 0, emissive: 0x0b4a46, emissiveIntensity: 1, clearcoat: 0.4, side: THREE.DoubleSide,
    });
    this.cutFace = new THREE.MeshStandardMaterial({ color: 0x4a505e, roughness: 0.85, emissive: 0x161a22, side: THREE.DoubleSide });
    const rd = reed();
    this.reed = new THREE.MeshPhysicalMaterial({
      color: 0xffffff, map: rd.map, normalMap: rd.normal, normalScale: new THREE.Vector2(0.35, 0.35),
      roughness: 0.5, metalness: 0, sheen: 0.6, sheenColor: new THREE.Color(0xffe2a0), sheenRoughness: 0.4,
      emissive: 0x3a2808, emissiveIntensity: 0.35, side: THREE.DoubleSide,
    });
    this.ligature = new THREE.MeshPhysicalMaterial({
      color: 0xdcdcd8, metalness: 1, roughness: 0.16, normalMap: bn, normalScale: new THREE.Vector2(0.04, 0.04), clearcoat: 0.3,
    });
    const ck = cork();
    this.cork = new THREE.MeshPhysicalMaterial({
      color: 0xffffff, map: tex(ck.map, 2, 1), normalMap: tex(ck.normal, 2, 1), normalScale: new THREE.Vector2(0.8, 0.8), roughness: 0.92, metalness: 0,
    });
    this.addXray(this.brass);
    this.addXray(this.rubber);
  }

  /** register a material (or a clone) to fade in X-ray mode */
  addXray(m: THREE.Material): void {
    this.xrayFade.add(m);
    if (this.xray) this.fade(m, true);
  }

  private fade(m: THREE.Material, on: boolean): void {
    m.transparent = on;
    m.opacity = on ? 0.14 : 1;
    m.depthWrite = !on;
    m.needsUpdate = true;
  }

  /** extra X-ray hooks (e.g. darkening the bore so the pressure colours read through the shell) */
  onXray(cb: (on: boolean) => void): void {
    this.xrayCbs.push(cb);
    cb(this.xray);
  }

  setXray(on: boolean): void {
    this.xray = on;
    for (const m of this.xrayFade) this.fade(m, on);
    this.brassDark.visible = !on;
    for (const cb of this.xrayCbs) cb(on);
  }

  get isXray(): boolean {
    return this.xray;
  }
}

/** Make a per-object material clone that supports hover/press emissive highlighting. */
export function highlightable<T extends THREE.MeshStandardMaterial>(m: T): T {
  const c = m.clone() as T;
  c.emissive = new THREE.Color(0x000000);
  return c;
}
